# Generated by Django 2.0.13 on 2020-09-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_vacation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('carde', models.CharField(max_length=10)),
                ('soldier1', models.CharField(max_length=10)),
                ('soldier2', models.CharField(max_length=10)),
                ('soldier3', models.CharField(max_length=10)),
                ('soldier4', models.CharField(max_length=10)),
                ('soldier5', models.CharField(max_length=10)),
            ],
        ),
    ]
