# Generated by Django 2.0.13 on 2020-08-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_vacation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='reason',
            field=models.CharField(choices=[('YG', '연가'), ('PS', '포상휴가'), ('WR', '위로휴가'), ('CW', '청원휴가')], default='YG', max_length=2),
        ),
    ]
