# Generated by Django 2.0.13 on 2020-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_vacation', '0002_nightworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('br_soldier1', models.CharField(max_length=10)),
                ('br_soldier2', models.CharField(max_length=10)),
                ('br_soldier3', models.CharField(max_length=10)),
                ('br_soldier4', models.CharField(max_length=10)),
            ],
        ),
    ]
