# Generated by Django 2.0.13 on 2020-08-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_vacation', '0003_menu_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='soldier',
            new_name='day_soldier',
        ),
        migrations.AddField(
            model_name='worker',
            name='night_soldier',
            field=models.TextField(default='wow'),
            preserve_default=False,
        ),
    ]
