# Generated by Django 2.0.13 on 2020-09-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_vacation', '0004_auto_20200903_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='washworker',
            old_name='br_soldier1',
            new_name='soldier1',
        ),
        migrations.RenameField(
            model_name='washworker',
            old_name='br_soldier2',
            new_name='soldier2',
        ),
        migrations.RenameField(
            model_name='washworker',
            old_name='br_soldier3',
            new_name='soldier3',
        ),
        migrations.RenameField(
            model_name='washworker',
            old_name='br_soldier4',
            new_name='soldier4',
        ),
    ]
