# Generated by Django 2.0.13 on 2019-12-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='fin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
