# Generated by Django 2.0.13 on 2019-12-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191205_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='is_fin',
            field=models.BooleanField(default=True),
        ),
    ]
